"""Markdown rendering for the AgentRx-style failure diagnosis."""

from __future__ import annotations

from collections import Counter

from diagnosis.labels import badge_for, label_for
from diagnosis.models import DiagnosisReport


def _category_breakdown_line(report: DiagnosisReport) -> str:
    """`🔴 2× Misinterpretation of Tool Output, 🟠 1× Underspecified Intent`.
    Empty string when nothing meaningful to show (≤ 1 distinct seed)."""
    counter = Counter(v.default_category_seed for v in report.violations if v.default_category_seed)
    if len(counter) < 2:
        return ""
    parts = [f"{badge_for(cat)} {count}× {label_for(cat)}" for cat, count in counter.most_common()]
    return "**Categories detected:** " + ", ".join(parts)


def render_diagnosis_md(report: DiagnosisReport) -> str:
    """Render the failure diagnosis as a Markdown section. Returns "" when
    the conversation succeeded with no audit-trail-worthy violations."""

    if report.succeeded and not report.violations:
        return ""

    lines: list[str] = ["## Failure Diagnosis", ""]

    if report.error_state:
        lines.append("> ⚠️ The LLM judge could not produce a verdict.")
        lines.append(f"> {report.error_message}")
        lines.append("")
    elif report.succeeded:
        lines.append(
            f"✅ **Conversation succeeded** — {len(report.violations)} non-critical "
            f"violation(s) recorded for the audit trail (all recovered)."
        )
        lines.append("")
    else:
        lines.append(f"❌ **Category:** {badge_for(report.category)} {label_for(report.category)}")
        lines.append(f"**Confidence:** {report.confidence.title()}")
        crit = report.critical_step_index
        lines.append(f"**Critical step:** position {crit if crit is not None else '—'}")
        lines.append(f"**Generated:** {report.generated_at.isoformat()}")
        lines.append(f"**Model:** {report.judge_model or 'heuristic-only (no LLM)'}")
        lines.append("")
        if report.summary:
            lines.append(report.summary)
            lines.append("")
        if report.reason_for_index:
            lines.append(f"> **Why this step:** {report.reason_for_index}")
            lines.append("")

    breakdown = _category_breakdown_line(report)
    if breakdown:
        lines.append(breakdown)
        lines.append("")

    if report.secondary_failures:
        lines.append("### Secondary findings (LLM judge)")
        lines.append("")
        lines.append("| Step | Category | Severity | Reason |")
        lines.append("| --: | :-- | :-- | :-- |")
        for sf in report.secondary_failures:
            reason = (sf.reason or "").replace("|", "\\|")[:160]
            lines.append(
                f"| {sf.step_index} | {badge_for(sf.category)} {label_for(sf.category)} | {sf.severity} | {reason} |"
            )
        lines.append("")

    if report.violations:
        lines.append("### Evidence")
        lines.append("")
        lines.append("| Step | Rule | Severity | Category | Description |")
        lines.append("| --: | :-- | :-- | :-- | :-- |")
        for v in report.violations:
            desc = (v.description or "").replace("|", "\\|")[:160]
            cat_cell = (
                f"{badge_for(v.default_category_seed)} {label_for(v.default_category_seed)}"
                if v.default_category_seed
                else "—"
            )
            lines.append(f"| {v.step_index} | `{v.rule_id}` | {v.severity} | {cat_cell} | {desc} |")
        lines.append("")

    if report.canned_recommendations:
        lines.append("### Recommendations (canned)")
        lines.append("")
        for rec in report.canned_recommendations:
            lines.append(f"- **{rec.title}** — {rec.body_md}")
        lines.append("")

    if report.llm_recommendations:
        lines.append("### Recommendations (AI-generated)")
        lines.append("")
        lines.append(f"_Generated by {report.judge_model or 'an LLM'}. Review before applying._")
        lines.append("")
        for rec in report.llm_recommendations:
            lines.append(f"- **{rec.title}** — {rec.body_md}")
        lines.append("")

    if report.redaction_summary:
        scrubbed = ", ".join(f"{k.lower()}: {v}" for k, v in sorted(report.redaction_summary.items()))
        lines.append(f"_Redacted before LLM call — {scrubbed}._")
        lines.append("")

    return "\n".join(lines)
